# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "des_training_project"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "default"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring seeds
# Full documentation: https://docs.getdbt.com/docs/building-a-dbt-project/seeds
seeds:
  # This declares that column names in the seed file will not be quoted when the table is created.
  +quote_columns: false

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In dbt, the default materialization for a model is a view. This means, when you run
# dbt run or dbt build, all of your models will be built as a view in your data platform.
# The configuration below will override this setting for models in the example folder to
# instead be materialized as tables. Any models you add to the root of the models folder will
# continue to be built as views. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:
  des_training_project:
    staging:
      +materialized: view
      +schema: staging
        # This configuration builds every model in the staging directory into a schema named staging_<target_schema>
        # learn more about custom schemas: https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-custom-schemas
      +query_tag: dbt_staging
        # This applies a query tag named `dbt_staging` to any related queries in Snowflake's Query_History
        # learn more about query tags: https://docs.getdbt.com/reference/resource-configs/snowflake-configs#query-tags
      
      tpch:
        +tags: "daily"
        # You can apply tags to models, snapshots, seeds. This allows you to run based on the tag such as `dbt run --model tag:daily` which would let you run all the models tagged "daily"
        # learn more about tags: https://docs.getdbt.com/reference/resource-configs/tags#definition
    
      jaffle_shop:
        +enabled: true
      
      stripe:
        +enabled: true
    
    intermediate:
      +schema: intermediate
      +materialized: view
      +query_tag: dbt_int

    marts:
      +query_tag: dbt_marts
      finance:
        +materialized: table
      marketing:
        +materialized: table
      sandwiches:
        +materialized: table